import React from 'react';
import { DailyRecord, ExpenseCategory } from '../types';

interface ShareableReportProps {
  record: DailyRecord;
  id: string; // To target with html2canvas
}

const calculateTotalExpenses = (record: DailyRecord) => {
    return record.expenses.reduce((total, category) => 
        total + category.items.reduce((catTotal, item) => catTotal + (item.amount || 0), 0), 
    0);
};

const CategoryCard: React.FC<{ category: ExpenseCategory }> = ({ category }) => {
    const categoryTotal = category.items.reduce((sum, item) => sum + item.amount, 0);
    const itemsWithAmount = category.items.filter(item => item.amount > 0);

    if (itemsWithAmount.length === 0) return null;

    // Use `break-inside-avoid` to prevent the card from splitting across columns.
    return (
        <div className="break-inside-avoid mb-4">
            <h4 className="text-sm font-semibold text-gray-800 bg-gray-100 p-2 rounded-t-md flex justify-between">
                <span className="pr-2">{category.name}</span>
                <span>₹{categoryTotal.toLocaleString('en-IN')}</span>
            </h4>
            <ul className="border border-t-0 border-gray-200 rounded-b-md">
                {itemsWithAmount.map((item, index) => (
                    <li key={item.id} className={`px-2 py-1 flex justify-between items-center text-xs ${index < itemsWithAmount.length - 1 ? 'border-b border-gray-100' : ''}`}>
                        <span className="text-gray-700 pr-2 break-words">{item.name}</span>
                        <span className="font-medium text-gray-800 flex-shrink-0">₹{item.amount.toLocaleString('en-IN')}</span>
                    </li>
                ))}
            </ul>
        </div>
    );
};

const ShareableReport: React.FC<ShareableReportProps> = ({ record, id }) => {
  const totalExpenses = calculateTotalExpenses(record);
  const profit = record.totalSales - totalExpenses;
  const morningSales = record.morningSales || 0;
  const nightSales = record.totalSales - morningSales;
  
  const categoriesWithExpenses = record.expenses.filter(category => 
    category.items.reduce((sum, item) => sum + item.amount, 0) > 0
  );
  
  // Note: We use strict standard colors (gray, white) here regardless of the app's theme
  // because this component is rendered off-screen specifically for image generation,
  // and we want the generated report to look like a clean, standard document (light mode)
  // regardless of user's dark mode setting.
  return (
    <div id={id} className="p-6 bg-white font-sans text-gray-800" style={{ width: '680px' }}>
      <div className="text-center pb-4 mb-4 border-b border-gray-200">
        <h1 className="text-xl font-bold text-purple-700">Ayshas Finance Tracker Report</h1>
        <p className="text-md text-gray-600 mt-1">{new Date(record.date + 'T00:00:00').toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>

      <div className="grid grid-cols-3 gap-4 text-center mb-6">
        <div className="bg-gray-50 p-3 rounded-lg flex flex-col justify-between">
            <div>
              <p className="text-xs font-medium text-gray-600">Total Sales</p>
              <p className="text-xl font-bold text-purple-700">₹{record.totalSales.toLocaleString('en-IN')}</p>
            </div>
             <div className="text-[10px] space-y-0.5 text-left border-t border-gray-200 pt-1.5 mt-1.5">
                <p className="flex justify-between"><span>Morning:</span> <span className="font-semibold text-gray-800">₹{morningSales.toLocaleString('en-IN')}</span></p>
                <p className="flex justify-between"><span>Night:</span> <span className="font-semibold text-gray-800">₹{nightSales.toLocaleString('en-IN')}</span></p>
            </div>
        </div>
        <div className="bg-gray-50 p-3 rounded-lg">
          <p className="text-xs font-medium text-gray-600">Total Expenses</p>
          <p className="text-xl font-bold text-red-600">₹{totalExpenses.toLocaleString('en-IN')}</p>
        </div>
        <div className="bg-gray-50 p-3 rounded-lg">
          <p className="text-xs font-medium text-gray-600">{profit >= 0 ? 'Profit' : 'Loss'}</p>
          <p className={`text-xl font-bold ${profit >= 0 ? 'text-green-700' : 'text-red-600'}`}>₹{Math.abs(profit).toLocaleString('en-IN')}</p>
        </div>
      </div>

      <div>
        <h3 className="text-lg font-semibold text-gray-800 text-center mb-4">Expense Breakdown</h3>
        <div className="text-left" style={{ columnCount: 2, columnGap: '1rem' }}>
          {categoriesWithExpenses.map(category => (
            <CategoryCard key={category.id} category={category} />
          ))}
        </div>
      </div>

       <div className="text-center mt-6 pt-3 border-t border-gray-200 text-xs text-gray-400">
        <p>Generated by Ayshas Finance Tracker</p>
      </div>
    </div>
  );
};

export default ShareableReport;