
import React from 'react';
import { DailyRecord } from '../types';

interface ShareableReportProps {
  record: DailyRecord;
  id: string; // To target with html2canvas
}

const calculateTotalExpenses = (record: DailyRecord) => {
    return record.expenses.reduce((total, category) => 
        total + category.items.reduce((catTotal, item) => catTotal + (item.amount || 0), 0), 
    0);
};

const ShareableReport: React.FC<ShareableReportProps> = ({ record, id }) => {
  const totalExpenses = calculateTotalExpenses(record);
  const profit = record.totalSales - totalExpenses;

  return (
    <div id={id} className="p-6 bg-white font-sans" style={{ width: '450px', color: '#1e293b' }}>
      <div className="text-center pb-4 mb-4">
        <h1 className="text-2xl font-bold text-primary">Aysha's P&L Report</h1>
        <p className="text-lg text-slate-600">{new Date(record.date).toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>

      <div className="grid grid-cols-3 gap-3 text-center mb-6">
        <div className="bg-slate-50 p-3 rounded-lg">
          <p className="text-sm font-medium text-slate-600">Total Sales</p>
          <p className="text-2xl font-bold text-primary">₹{record.totalSales.toLocaleString('en-IN')}</p>
        </div>
        <div className="bg-slate-50 p-3 rounded-lg">
          <p className="text-sm font-medium text-slate-600">Total Expenses</p>
          <p className="text-2xl font-bold text-error">₹{totalExpenses.toLocaleString('en-IN')}</p>
        </div>
        <div className="bg-slate-50 p-3 rounded-lg">
          <p className="text-sm font-medium text-slate-600">{profit >= 0 ? 'Profit' : 'Loss'}</p>
          <p className={`text-2xl font-bold ${profit >= 0 ? 'text-success' : 'text-error'}`}>₹{Math.abs(profit).toLocaleString('en-IN')}</p>
        </div>
      </div>

      <div className="space-y-3">
        <h3 className="text-lg font-semibold text-slate-800 text-center mb-2">Expense Breakdown</h3>
        {record.expenses.map(category => {
          const categoryTotal = category.items.reduce((sum, item) => sum + item.amount, 0);
          if (categoryTotal === 0) return null;
          return (
            <div key={category.id}>
              <h4 className="text-md font-semibold text-slate-700 bg-slate-100 p-2 rounded-t-md flex justify-between">
                <span>{category.name}</span>
                <span>₹{categoryTotal.toLocaleString('en-IN')}</span>
              </h4>
              <ul className="border border-t-0 border-slate-200 rounded-b-md">
                {category.items.filter(item => item.amount > 0).map((item, index, arr) => (
                  <li key={item.id} className={`px-2 py-1 flex justify-between items-center text-sm ${index < arr.length - 1 ? 'border-b border-slate-100' : ''}`}>
                    <span className="text-slate-700">{item.name}</span>
                    <span className="font-medium text-slate-800">₹{item.amount.toLocaleString('en-IN')}</span>
                  </li>
                ))}
              </ul>
            </div>
          );
        })}
      </div>
       <div className="text-center mt-6 pt-4 border-t border-slate-200 text-xs text-slate-400">
        <p>Generated by Aysha's P&L Dashboard</p>
      </div>
    </div>
  );
};

export default ShareableReport;
